"""Add type, health_score, and meta_info to System model

Revision ID: 75675e441818
Revises: 
Create Date: 2025-10-07 22:06:07.636993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75675e441818'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('capabilities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))

    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('health_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('meta_info', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.drop_column('meta_info')
        batch_op.drop_column('health_score')
        batch_op.drop_column('type')

    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_column('config')
        batch_op.drop_column('capabilities')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
