"""Add client_access_key_encrypted field to agent_instances

Revision ID: decbf1c017f7
Revises: fc21977e9644
Create Date: 2025-10-09 07:17:42.281000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decbf1c017f7'
down_revision = 'fc21977e9644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_access_key_encrypted', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_instances', schema=None) as batch_op:
        batch_op.drop_column('client_access_key_encrypted')

    # ### end Alembic commands ###
