"""Add Azure Speech fields to AgentInstance

Revision ID: fc21977e9644
Revises: 7edc019668be
Create Date: 2025-10-08 07:09:30.409463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc21977e9644'
down_revision = '7edc019668be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('azure_speech_endpoint', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('azure_speech_key_secret_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('azure_speech_region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('azure_speech_voice_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_instances', schema=None) as batch_op:
        batch_op.drop_column('azure_speech_voice_name')
        batch_op.drop_column('azure_speech_region')
        batch_op.drop_column('azure_speech_key_secret_id')
        batch_op.drop_column('azure_speech_endpoint')

    # ### end Alembic commands ###
